### ISSUE TITLE
Login doesn't work anymore

### ISSUE THREAD

**Issue by dictyo** [edzillion/circles_testnet#5]
## Device
Android Emulator API 22, which is Android 5.1 or real Samsung S4Mini or Note4

## Commit 
master-branch 18d0368 from 24.06.16:00 => A release or another tag after some bigger changes would be helpful

## Precondition:
I open a fresh app, pass splash screen and Login Screen is shown.

## Steps
1. BUG: Push "Login with Email" => Click is shown, but screen doesn't change
=>LOG entries provoked by click:
06-24 16:15:06.720 4124-4124/com.edzillion.circles_testnet I/chromium: [INFO:CONSOLE(590)] "ERROR", source: ng:///LoginEmailPageModule/LoginEmailPage.ngfactory.js (590)
06-24 16:15:06.730 4124-4124/com.edzillion.circles_testnet I/chromium: [INFO:CONSOLE(590)] "ERROR CONTEXT", source: ng:///LoginEmailPageModule/LoginEmailPage.ngfactory.js (590)
06-24 16:15:36.782 4124-4124/com.edzillion.circles_testnet I/chromium: [INFO:CONSOLE(590)] "ERROR", source: ng:///LoginEmailPageModule/LoginEmailPage.ngfactory.js (590)
06-24 16:15:36.822 4124-4124/com.edzillion.circles_testnet I/chromium: [INFO:CONSOLE(590)] "ERROR CONTEXT", source: ng:///LoginEmailPageModule/LoginEmailPage.ngfactory.js (590)

## Postcondition
Wenn I first click "register" and then press "Back" I get to the email-login-screen (and many others created invisibly by pushing the buttin in step 3.)

Login by Facebook and Google might be not working, too.

**Comment by edzillion** [comment]
Apologies, I had forgotten to update the html for that page when I did a refactor/beautify sweep.

Fixed in https://github.com/edzillion/circles_testnet/commit/00710d404dcee54edcbaae40ed644f32f24b4763

Also, what are you using to debug? I am using `chrome://inspect/#devices`

**Comment by dictyo** [comment]
Great fix, seems everything is fine again. I even was able to publish my first offer. :)

After getting embroiled too much first in Docker I found out, that my Windows-Env with Android Studio and Node make it just a step of five minutes to get going with ionic. So right now I'm still exploring the Intellij-GUI for debugging- and performance measuring options. 
But for hot-deployment and quick test of code-changes I'd use Chrome-inspect, too, I suppose.
